#!/bin/bash

STREAMLINK='streamlink --wwenetwork-email=rgorojovsky@gmail.com --wwenetwork-password=s0rru79 --player-no-close' # --loglevel debug

if [ -z $1 ]; then
	$STREAMLINK http://watch.wwe.com/channel/2026 best 
else
	$STREAMLINK $1 best
fi

